[features]
seeds = false
skip-lint = false
[programs.devnet]
demo = "9oJDq3FPjoH72bvqKkyfNyoHCyZPeraMtQxZjKGRjJtY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yanaemons/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"